#_*_coding:utf-8_*_
__author__ = 'jidong'

from django.conf.urls import patterns, include, url

urlpatterns = patterns('iasset.views',
    url(r'^index$', 'asset_index', name='asset_index'),
    url(r'^list/$', 'asset_list', name='asset_list'),
    url(r'^add/$', 'asset_add', name='asset_add'),
    url(r'^add/(.+)',"asset_add_alltype"),
    url(r"^add_batch/$", 'asset_add_batch', name='asset_add_batch'),
    url(r'^delete/$', 'asset_delete', name='asset_delete'),
    url(r"^detail/$", 'asset_detail', name='asset_detail'),
    url(r"^detail/blade/(?P<asset_name>\w+)/$", 'asset_detail_blade', name='asset_detail_blade'),
    url(r"^detail/bladecenter/(?P<asset_name>\w+)/$", 'asset_detail_bladecenter', name='asset_detail_bladecenter'),
    url(r"^detail/network/(?P<asset_name>\w+)/$", 'asset_detail_network', name='asset_detail_network'),
    url(r"^detail/others/(?P<asset_name>\w+)/$", 'asset_detail_others', name='asset_detail_others'),
    url(r"^detail/parts/(?P<asset_name>\w+)/$", 'asset_detail_parts', name='asset_detail_parts'),
    url(r"^detail/security/(?P<asset_name>\w+)/$", 'asset_detail_security', name='asset_detail_security'),
    url(r"^detail/server/(?P<asset_name>\w+)/$", 'asset_detail_server', name='asset_detail_server'),
    url(r"^detail/storage/(?P<asset_name>\w+)/$", 'asset_detail_storage', name='asset_detail_storage'),
    url(r"^detail/tape/(?P<asset_name>\w+)/$", 'asset_detail_tape', name='asset_detail_tape'),
    url(r"^detail/vm/(?P<asset_name>\w+)/$", 'asset_detail_vm', name='asset_detail_vm'),
    # url(r'^edit/$', 'asset_edit', name='asset_edit'),
    # url(r'^edit_batch/$', 'asset_edit_batch', name='asset_edit_batch'),
    url(r'^update/$', 'asset_update', name='asset_update'),
    url(r'^update_batch/$', 'asset_update_batch', name='asset_update_batch'),
    # url(r'^manage/$', 'asset_manage', name='asset_manage'),
    url(r'^manage/$', 'manage_idc', name='asset_manage'),
    url(r'^manage/idc/$', 'manage_idc', name='manage_idc'),
    url(r'^manage/idc/list$', 'manage_idc_list', name='manage_idc_list'),
    url(r'^manage/idc/add$', 'manage_idc_add', name='manage_idc_add'),
    url(r'^manage/idc/edit$', 'manage_idc_edit', name='manage_idc_edit'),
    url(r'^manage/idc/delete$', 'manage_idc_delete', name='manage_idc_delete'),
    url(r'^manage/os/$', 'manage_os', name='manage_os'),
    url(r'^manage/os/add/$', 'manage_os_add', name='manage_os_add'),
    url(r'^manage/os/list/$', 'manage_os_list', name='manage_os_list'),
    url(r'^manage/os/edit/$', 'manage_os_edit', name='manage_os_edit'),
    url(r'^manage/os/delete/$', 'manage_os_delete', name='manage_os_delete'),
    url(r'^manage/cabinet/$', 'manage_cabinet', name='manage_cabinet'),
    url(r'^manage/cabinet/add/$', 'manage_cabinet_add', name='manage_cabinet_add'),
    url(r'^manage/cabinet/list/$', 'manage_cabinet_list', name='manage_cabinet_list'),
    url(r'^manage/cabinet/edit/$', 'manage_cabinet_edit', name='manage_cabinet_edit'),
    url(r'^manage/cabinet/delete/$', 'manage_cabinet_delete', name='manage_cabinet_delete'),
    # url(r'^manage/tag/$', 'manage_tag', name='manage_tag'),

    url(r'^detail/(?P<asset_type>\w+)/(?P<asset_name>\w+)/(?P<item>\w+)/(?P<action>\w+)/$', 'asset_detail_item_action', name='asset_detail_item_action'),

    # url(r'^detail/(?P<asset_type>\w+)/(?P<asset_name>\w+)/ports$','asset_detail_ports_list',name='asset_detail_ports_list'),
    # url(r'^detail/(?P<asset_type>\w+)/(?P<asset_name>\w+)/ports/add/$','asset_detail_ports_add',name='asset_detail_ports_add'),
    # url(r'^detail/(?P<asset_type>\w+)/(?P<asset_name>\w+)/ports/edit/$','asset_detail_ports_edit',name='asset_detail_ports_edit'),
    # url(r'^detail/(?P<asset_type>\w+)/(?P<asset_name>\w+)/ports/delete/$','asset_detail_ports_delete',name='asset_detail_ports_delete'),
    # url(r'^detail/(?P<asset_type>\w+)/(?P<asset_name>\w+)/parts$','asset_detail_parts_list',name='asset_detail_parts_list'),
    # url(r'^detail/(?P<asset_type>\w+)/(?P<asset_name>\w+)/parts/add/$','asset_detail_parts_add',name='asset_detail_parts_add'),
    # url(r'^detail/(?P<asset_type>\w+)/(?P<asset_name>\w+)/parts/edit/$','asset_detail_parts_edit',name='asset_detail_parts_edit'),
    # url(r'^detail/(?P<asset_type>\w+)/(?P<asset_name>\w+)/parts/delete/$','asset_detail_parts_delete',name='asset_detail_parts_delete'),

)